version: '3.9'

services:
 db:
  container_name: postgres_db
  image: postgres:alpine
  restart: unless-stopped
  ports:
   - 8000:5432
  volumes:
   - ./logs:/var/log
  environment:
   - POSTGRES_DB=advt_db
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres -d pythonapp_db"]
   interval: 1m30s
   timeout: 30s
   retries: 5
   start_period: 30s